version: '3.1'

services:
  postgres:
    image: divyenduz/postgres-with-data:0.0.2
    restart: always
    command: postgres -c 'max_connections=1' -c 'superuser_reserved_connections=0'
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
